#!/bin/bash

#MDBFILE="BK_Nicoya.mdb"

#OPTIONS="-H -D %y-%m-%d"
#mdb-export $OPTIONS $MDBFILE  LogParameters >  output_1.txt
find . -name "* *" | rename 's/ /_/g'
find -name "*.mdb" -type f -exec bash -c 'mdb-export $0  "Data Log # 1" >  $0.dlog1.csv' {} \;
find -name "*.mdb" -type f -exec bash -c 'mdb-export $0  "Data Log # 2" >  $0.dlog2.csv' {} \;

